version: '3.8'

services:
  portfolio:
    image: ghcr.io/irineualmeidajr/portifolio-3d:latest
    container_name: portfolio-3d-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    networks:
      - web
    labels:
      # Headers de segurança
      - "traefik.http.middlewares.security-headers.headers.frameDeny=true"
      - "traefik.http.middlewares.security-headers.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.security-headers.headers.browserXssFilter=true"
      - "traefik.http.middlewares.security-headers.headers.referrerPolicy=strict-origin-when-cross-origin"
      - "traefik.http.routers.portfolio-3d-app.middlewares=security-headers"
    
      - "traefik.enable=true"
      - "traefik.http.routers.portfolio-3d-app.rule=Host(`roinusoftware.com`) || Host(`www.roinusoftware.com`)"
      - "traefik.http.routers.portfolio-3d-app.entrypoints=websecure"
      - "traefik.http.routers.portfolio-3d-app.tls=true"
      - "traefik.http.routers.portfolio-3d-app.tls.certresolver=lets-encrypt"
      - "traefik.http.services.portfolio-3d-app.loadbalancer.server.port=3000"
      - "traefik.docker.network=web"     

      # Redirecionamento HTTP -> HTTPS
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.portfolio-3d-app-http.rule=Host(`roinusoftware.com`)"
      - "traefik.http.routers.portfolio-3d-app-http.entrypoints=web"
      - "traefik.http.routers.portfolio-3d-app-http.middlewares=https-redirect"

networks:
  web:
    external: true
